### ISSUE TITLE
Cardinality question

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#137]
1. reading [here](https://github.com/buildingSMART/IDS/blob/master/Documentation/developer-guide.md#optionality):

![grafik](https://user-images.githubusercontent.com/59165496/226211453-f638f561-ebb7-4e4a-b9d4-7dbc2fb79a68.png)

2. and looking at the example [here](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-classification.md#pass-a-required-facet-checks-all-parameters-as-normal):

![grafik](https://user-images.githubusercontent.com/59165496/226211503-436bb4c5-4e41-45c3-825f-c2bf95389621.png)

-> I wonder: what does the combination `minOccurs="1"` with `maxOccurs="1"` mean?

**Comment by aothms** [comment]
Good point.

We specifically discussed that wouldn't want to support cases like "For wall I need exactly two properties" even if the schema would allow that (hence the table).

This is first and foremost in the `required` category.

There's several questions here I guess:
- Should the docs be updated?
  - State maxOccurs can be "1 or unbounded" for the required case (or leave it empty)? To disambiguate requiring exactly one or at least one?
  - Should the statement "they do not have any meaning" be refined? What does it mean: Is it allowed? Implementation dependent?
- Is it ever meaningful to require an upperbound other than zero (because the docs seem to say "no" and I can live with that answer). In that case maybe it's better to *require* maxOccurs to be set to unbounded as the table suggests.

My take on this is: change the sentence to "other permutations are currently not allowed" and update the sample to unbounded.

**Comment by CBenghi** [comment]
#147 has been merged. This issue can be closed.

**Comment by pjanck** [comment]
The examples weren't updated, thus making them invalid (compare https://github.com/buildingSMART/IDS/pull/147/commits/17f3b66a11330072c6bc38e2019405f03890be1f with point 2 above). I request to reopen the issue / should I open a new one?

**Comment by berlotti** [comment]
We prefer you fix the examples and create a pull request

**Comment by CBenghi** [comment]
@berlotti and @pjanck,
As part of the auditing tool I'm writing, I'll take care of creating a new PR soon with the fixes for the Development files.
I'll need to liaise with @Moult for the testcases because they are programmatically generated outside of this repository.
