### ISSUE TITLE
When will IDS version 1.0 be released?

### ISSUE THREAD

**Issue by Martin15135215** [buildingSMART/IDS#182]
I have this question because at the moment my company is asking whether to use IDS.

The information about when we will get to IDS version 1.0 is helpful for our planning.

Thanks a lot for the great work !

**Comment by berlotti** [comment]
Formally the IDS specification is now in the 'software validation' phase. This is on hold a bit in the vacation period, but will start regular meetings soon.
The intent of this phase is to prove that the standard is implementable. With so many implementations already available it will be hard to find a vendor that can review this with a fresh look (could you be one of those?).

Since the scope has been clearly defined, and a lot of implementations already available, we expect the current XSD to become the 1.0 version.
This has to be approved by the buildingSMART Standards committee in a formal vote that takes 12 weeks.

**Comment by Martin15135215** [comment]
Thank you very much for the informative answer!

I myself do not work in a software company, but out of my own curiosity I have already [created IDS file with IfcTester](https://community.osarch.org/discussion/1601/ids-creating-an-ids-file-with-a-python-script#latest) and tested it with an IFC file using the same library. 

At the moment, my company is in the analysis phase for a future process on how to increase the data quality of the IFC we receive from the planners. IDS is a good candidate and I am happy to hear that many software vendors already support this and that IDS version 1.0 will be released in the near future.
