### ISSUE TITLE
Use of "Prohibited" type

### ISSUE THREAD

**Issue by mysterieux30** [buildingSMART/IDS#186]
Hello, i just have a tiny question concerning the following example shown under the testcases-ids.md file (Link: [https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-ids.md#pass-prohibited-specifications-fail-if-at-least-one-entity-passes-all-requirements-13](url))

Does the following specification in this case mean that ALL NON IFCWALL entities must have exactly 1 Name attribut with "Waldo" as value, or does it just mean that IFCWALL entities may not have Name attribut with "Waldo" as value?

`<specifications>
    <specification name="Name" ifcVersion="" minOccurs="0" maxOccurs="0">
        <applicability>
            <entity>
                <name>
                    <simpleValue>IFCWALL</simpleValue>
                </name>
            </entity>
        </applicability>
        <requirements>
            <attribute minOccurs="1" maxOccurs="1">
                <name>
                    <simpleValue>Name</simpleValue>
                </name>
                <value>
                    <simpleValue>Waldo</simpleValue>
                </value>
            </attribute>
        </requirements>
    </specification>
</specifications>`

       `#1=IFCSLAB('1hqIFTRjfV6AWq_bMtnZwI',$,'Waldo',$,$,$,$,$,$);`

**Comment by Moult** [comment]
Prohibited specifications mean "this information must not be found".

Therefore it says "I must not have any walls named Waldo". The IFC has a slab named waldo, which is totally cool, since it's not a wall.

> or does it just mean that IFCWALL entities may not have Name attribut with "Waldo" as value?

^ so yes, this is what it means.

See https://github.com/buildingSMART/IDS/blob/master/Documentation/specifications.md#required-and-optional-specifications-and-facets
