### ISSUE TITLE
Location setting: "type". What does it mean for model checking?

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#22]
If checking existance of properties I normally do not care if it is attached to the occurrence (IfcObject) or type (IfcTypeObject). 

If restricting the requirements to "type" does it automatically mean that this information shall not be available on the occurrence level?

**Comment by berlotti** [comment]
When the requirement states information needs to be linked to type, than that is the requirement.
It does not state anything about occurrences.

**Comment by MatthiasWeise** [comment]
How does that fit to the override agreement in IFC? 
If I redefine on occurrence level, the information attached on type level will be ignored and thus will be irrelevant.

**Comment by berlotti** [comment]
Good question. This depends on how the users interprets it. 
Some might feel the IDS overrides the override agreement, but in practice (coming from the use-case analysis) these occurrences are defined under a different requirement.

**Comment by aothms** [comment]
This has also been discussed in the meetings. One possible interpretation is that a location=type attribute implies that there must not be overrides in the file on the occurrence level for that property. Without a location attribute the rule should follow the IFC override agreements.

**Comment by MatthiasWeise** [comment]
_"Without a location attribute .."_ -> I guess you mean the "any" setting (location is a required attribute in the schema). 

Following the IFC override rule makes sense in any case. So, I also agree with the interpretation: _"a location=type attribute implies that there must not be overrides in the file on the occurrence level for that property"_ 

Anyhow, it needs to be agreed and then documented in the specs.

**Comment by aothms** [comment]
>  I guess you mean the "any" setting (location is a required attribute in the schema).

Indeed, thanks for eliminating the confusion

**Comment by Moult** [comment]
I just got linked this because I had the same question.

I see two possible interpretations:

Interpretation 1: the Location setting is unnecessary and can be removed. When specifying an applicability based on a property, the IFC rules on property inheritance and overrides applies. If you specify on an attribute or something which doesn't inherit, then you don't follow the inheritance rules - that's simply how IFC works. E.g.

```
Applicability
    Entity: IfcWall
    Note: No Location setting at all. Deleted from IDS.
    Property: Pset_Foo.Bar = "Baz"

PASS: IfcWall [Pset_Foo.Bar = "Baz"]
PASS: IfcWall <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "Baz"]
PASS: IfcWall [Pset_Foo.Bar = "Baz"] <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "NotBaz"]

Applicability
    Entity: IfcWall
    Note: No Location setting at all. Deleted from IDS.
    Attribute: Foo = "Bar"

PASS: IfcWall [Foo = "Bar"]
FAIL: IfcWall <- IfcRelDefinesByType -> IfcWallType [Foo = "Bar"]
PASS: IfcWall [Foo = "Bar"] <- IfcRelDefinesByType -> IfcWallType [Foo = "NotBar"]
```

Interpretation 2: the Location setting is actually a way to specify an applicability of occurrences of a type that passes your applicability criteria. For example, I might want my specification to be applicable to only the walls of a particular series of wall types:

```
Applicability
    Entity: IfcWall
    Location: type
    Property: Pset_Foo.Bar = "Baz"

FAIL: IfcWall [Pset_Foo.Bar = "Baz"]
PASS: IfcWall <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "Baz"]
FAIL: IfcWall [Pset_Foo.Bar = "Baz"] <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "NotBaz"]

Applicability
    Entity: IfcWall
    Location: type
    Attribute: Foo = "Bar"

FAIL: IfcWall [Foo = "Bar"]
PASS: IfcWall <- IfcRelDefinesByType -> IfcWallType [Foo = "Bar"]
FAIL: IfcWall [Foo = "Bar"] <- IfcRelDefinesByType -> IfcWallType [Foo = "NotBar"]

Applicability
    Entity: IfcWall
    Location: instance
    Property: Pset_Foo.Bar = "Baz"

PASS: IfcWall [Pset_Foo.Bar = "Baz"]
FAIL: IfcWall <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "Baz"]
PASS: IfcWall [Pset_Foo.Bar = "Baz"] <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "NotBaz"]

Applicability
    Entity: IfcWall
    Location: instance
    Attribute: Foo = "Bar"

PASS: IfcWall [Foo = "Bar"]
FAIL: IfcWall <- IfcRelDefinesByType -> IfcWallType [Foo = "Bar"]
PASS: IfcWall [Foo = "Bar"] <- IfcRelDefinesByType -> IfcWallType [Foo = "NotBar"]

Applicability
    Entity: IfcWall
    Location: any
    Property: Pset_Foo.Bar = "Baz"

PASS: IfcWall [Pset_Foo.Bar = "Baz"]
PASS: IfcWall <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "Baz"]
PASS: IfcWall [Pset_Foo.Bar = "Baz"] <- IfcRelDefinesByType -> IfcWallType [Pset_Foo.Bar = "NotBaz"]

Applicability
    Entity: IfcWall
    Location: any
    Attribute: Foo = "Bar"

PASS: IfcWall [Foo = "Bar"]
PASS: IfcWall <- IfcRelDefinesByType -> IfcWallType [Foo = "Bar"]
PASS: IfcWall [Foo = "Bar"] <- IfcRelDefinesByType -> IfcWallType [Foo = "NotBar"]
```

I find the second interpretation really confusing and goes against the well-established notion of when inheritance applies and when inheritance doesn't apply.

My gut feel (sorry, still new to reading this spec) is that interpretation 1 is what people would expect because that's just how IFC works, and so the Location setting should be deleted.

Thing | Behaviour
--- | ---
Attribute | Explicit
Properties | Inheritance & override applies
Materials | Inheritance & override applies
PredefinedType | Inheritance & override applies
Classification | Inheritance & override applies (I assume only, I cannot find an explicit sentence for this in the IFC docs)

**Comment by Moult** [comment]
A further elaboration in favour of just deleting the Location attribute: IFC has specified the rules on inheritance and overrides since IFC2X3 - I find it very odd that IDS can specify something against this established convention. Not only is this a long established convention in IFC, it's also a convention in construction terminology and similar to the language a project manager might use in contractual specifications. Any AEC professional knows that if a door type has property X, then all occurrences of that door also inherits property X unless I tell you otherwise (override). This is an industry convention established since probably forever :)

So I find it strange that you might say "I want doors with property X, but only if I specify it on the type".

Would be very interested to hear the usecases why Location has a use.

**Comment by aothms** [comment]
I think it's not so much about inheritance and semantics. It's more about the potential to precisely stipulate where information can be retrieved from the model.

Also note that when not considering pset templates or psets from the spec, there is no overriding mechanism explicitly defined. So for a given property, establishing `location=type maxOccurs=0`, `location=occurrence maxOccurs=1` would be an IDS mechanism to define OCCURENCEDRIVEN or with the attributes reversed would be TYPEDRIVEN. There's some value in that probably if you consider IDS as a means for defining pset templates.

I must say that at the time of the initial discussions I was also more on the side of "let IFC define the mechanisms and semantics" and "let IDS constrain the implied outcome", but I guess in a lot of cases it's also valid to ignore the "mechanisms and semantics" and consider IFC as just a container of data that you'd want to precisely constrain.

**Comment by Moult** [comment]
> There's some value in that probably if you consider IDS as a means for defining pset templates.

Good point. Agreed.

What is the meaning of "any" then - is it "type OR occurrence" or is it "type, unless overridden by occurrence"?

I'm just worried someone is going to specify "this is applicable to all fire rated doors", choose "type", and then in any IFC viewer which implements inheritance, they're going to miss out on overridden doors. Or they might choose "occurrence" and then they'd miss out on inherited doors, when they might actually mean "I just want fire rated doors".

Similarly, PSET_TYPEDRIVENOVERRIDE is the majority, so what if a user doesn't understand this and chooses "instance" or "type", which contradicts with PSET_TYPEDRIVENOVERRIDE. Or what if the pset is PSET_OCCURRENCEDRIVEN but they choose "type"? This places a huge responsibility on the user to know the template they are using... and they'll likely get it wrong. Why not just remove this risk?

> Also note that when not considering pset templates or psets from the spec, there is no overriding mechanism explicitly defined.

The definition is "NOTDEFINED", which seems to be (from IfcPropertySetTemplateTypeEnum):

> No restriction provided, the property sets defined by this [IfcPropertySetTemplate](http://localhost:5000/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPropertySetTemplate.htm) can be assigned to any entity, if not otherwise restricted by the ApplicableEntity attribute.

I see no difference between NOTDEFINED and PSET_TYPEDRIVENOVERRIDE/QTO_TYPEDRIVENOVERRIDE. Yes technically they don't use the word "OVERRIDE" but what does it mean for an occurrence to say it has a fire rating of 1hr and the type to have a fire rating of 2hrs? It seems rather meaningless, so I'd equate it to TYPEDRIVENOVERRIDE.

**Comment by aothms** [comment]
I agree, if we proceed with this we may need some sort of "truth table" as

    (NOTDEFINED, TYPEDRIVENOVERRIDE, TYPEDRIVEN, OCCURENCEDRIVEN)
                                                     x
    (no matching property, property on type, property on occurence, same value on both, property different value on both)

and then the required behaviour in every cell.

I'm also fine to revisit this discussion. My recollection: There wasn't really consensus that this was needed. There just wasn't a lot of opposition because we all thought it's a trivial thing and most people would keep it at `any`.

**Comment by MatthiasWeise** [comment]
Please allow a general comment. 

Following the discussion I see conflicting requirements. The override discussion seems to me to origin from the need to specify "user defined properties" - similar to the discussion about units. This is somehow in conflict of having property templates in IFC itself allowing to specify that in all details. 

Another conflict seems to come from idea to somehow abstract requirements in IDS from implementation details in IFC. This makes the specification easier to read for normal users, but of course adds the need to agree on those implementation details in IFC. As already mentioned in another post this adds the challenge of unclear interpretation unless with have a formal mapping as for instance in mvdXML. While the challenge of proper interpretation remains in IDS, adding a bunch of additional parameters for tweaking the mappings makes things more complicated (for both definition and implementation). And here we are just talking about Single Value Properties, think about material requirements. 

The promise of IDS was to keep it simple and focus on most crucial parts. My feeling is that we are starting to overload IDS with nice to have features. Seeing such wishes is not really a surprise, but we should be clear about the consequences in a longer run if IDS wants to be more close to the IFC implementation details.

**Comment by TLiebich** [comment]
this discussion provokes a general question - are we still on track? My take from the beginning of the IDS work was, that it defines a straight forward, easy to implement, specification to verify information deliveries, that are imposed by an information delivery specification (sort of IDM or LOI(N), if you want).

I don't know any real life information delivery specifications, that would differentiate whether the required property within a discipline model delivered for a certain milestone is occurrence driven, type driven, or type driven override, or similar. It is either provided, or not, according to the principles of the IFC standard and should have a value within stated constraints.

So I completely follow @Moult interpretation 1, and the position of @MatthiasWeise. And in my interpretation of the scope for IDS, such "location" is simply out of scope.

If the target is to support a software certification or deep testing of an IFC data file population, where such distinction makes sense, we should stick with mvdXML (best mvdXML1.2), since it is designed for exactly this purpose (using the concept templates from the IFC specification), and not trying to redevelop a "semi-light. still verbose" IDS specification as a replacement. Lets keep the scope and purpose of both specifications separate.

**Comment by berlotti** [comment]
The IDS development seems to be following the 'normal' evolution of a standard. Start simple; make the mistake of expanding into too many details; trying to get back to 'simple' again.

In the last meeting the 'use' and 'necessity' attributes moved away and have been replaced by the minOccurs and maxOccurs.  It seems that the 'location' attribute was a 'simple and small' addition originally but turns out to be too complex without too big added value. 
I would support the removal from the standard but only when we would define and document the nominal behaviour then.

**Comment by Moult** [comment]
Looking for some closure for this, I completely agree with @TLiebich especially this statement:

> I don't know any real life information delivery specifications, that would differentiate whether the required property within a discipline model delivered for a certain milestone is occurrence driven, type driven, or type driven override, or similar. It is either provided, or not, according to the principles of the IFC standard and should have a value within stated constraints.

So I propose to remove "Location" and the default behaviour is the only valid behaviour: the IFC defined behaviour.

**Comment by rubendel** [comment]
Assuming that when "Location" is removed the interpretation will always be "Option 2", I am in favor.

**Comment by Moult** [comment]
@rubendel yes, Option 2 is the IFC defined behaviour which has been well-established since IFC began, so... yes, +1 on removing Location which means option 2. Or, if for some reason Location stays (can someone provide a usecase?) Option 2 should still be specified IMHO.

**Comment by MatthiasWeise** [comment]
I agree with removing the "Location" and going with the IFC agreement (option 2).
