### ISSUE TITLE
Extended Relationship Facet

### ISSUE THREAD

**Issue by NickNisbet** [buildingSMART/IDS#248]
I would like to specify
B. That every significant element should have type. 

Both as an applicability (anything with a Type should have a quantity) and as a requirement (anything bigger than 0.1m3 should have a type object.

**Comment by MatthiasWeise** [comment]
New feature for IDS 2.0?
However, I wonder if such kind of checks should be covered by IDS at all. By design IDS wants to hide schema details from the user to be easy to use. Main focus is on availability/correctness of content, but not how it is encoded in IFC (property attached to occurrence or type object does not matter).

**Comment by pjanck** [comment]
> I wonder if such kind of checks should be covered by IDS at all

Agreed. This is outside of scope of IDS in my perception as well (even for 2.0).

> every significant element should have type

@NickNisbet I propose to use mvdXML to require this.

**Comment by CBenghi** [comment]
Indeed, 
here we want to make sure that the information is provided.
As long as it's provided according to the IFC best practice, we should be satisfied.
Let IFC deal with file quality, we are all about information!
