### ISSUE TITLE
Remove sample that is checking wall types

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#253]
It is not advisable to target type classes in IFC, since:

1. The users may not be aware of them
2. The users may not have control over them in the authoring tools

I'd get rid of [this](https://github.com/buildingSMART/IDS/tree/master/Documentation/library) sample.

**Comment by NickNisbet** [comment]
I learnt today from a user that that Solibri does not currently support it.
This is an important use case:  to check that properties have not been assigned to inappropriate IFC entities.
So it helps with information requirements for any downstream process that is going to use the property or filter the model.
In most applications a user DOES have control and they WILL need to be aware of this if  it is wrong.
Please don’t remove it .
Please improve Solibri to support it.


Regards,

Nick.


From: pasi-paasiala ***@***.***>
Sent: 28 February 2024 13:02
To: buildingSMART/IDS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [buildingSMART/IDS] Remove sample that is checking wall types (Issue #253)


EXTERNE-EMAIL Bitte klicken Sie nicht auf Links oder öffnen Sie keine Anhänge! Es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.

It is not advisable to target type classes in IFC, since:

  1.  The users may not be aware of them
  2.  The users may not have control over them in the authoring tools

I'd get rid of this<https://github.com/buildingSMART/IDS/tree/master/Documentation/library> sample.

**Comment by CBenghi** [comment]
@pasi-paasiala,
the choice to be able to target all IFC classes (limited to the appropriate applicable facets) was made long ago.
I think there's no reason to restrict it in 0.9.7, the implications would be huge.

Are you ok to close this issue?
