### ISSUE TITLE
case sensitivity for values

### ISSUE THREAD

**Issue by berlotti** [buildingSMART/IDS#30]
Are the values in the xml nodes case sensitive or not? 
Or should we add an attribute to define case sensitivity? Per node or per IDS?

**Comment by dro007** [comment]
This depends on who our target market is. If we are supporting software engineers who are used to typing in camel case then case sensitivity would be ok. 
If we want to support "normal" people, then case sensitivity would be extremely frustrating for them. There could be development environments that supported validating case sensitivity for "normal" people, but this adds another layer of complexity.

**Comment by aothms** [comment]
My thoughts:

* entity predefined type are special since they refer to existing definitions. I'd say they need to be case-insensitive, as EXPRESS is also case insensitive and it allows people to copy paste from both the mixed case docs as well as upper case serialization.
* some pset names are standardized others aren't. Maybe it should be forced case insensitive. I think errors are easily made there and there is no value in differencing case. Same for the property names.
* for most other cases I'd say it's up to the user, so I'd say an attribute is best
* we need to consider what to do with the combination of case insensitivity and pattern. So we could either say case-sensitive is an attribute of e.g simpleValue and enum so that pattern is by definition case sensitive, but that would allow case-sensitivity specification on entity. Attribute can also be on facet nodes.
* Keep in mind that you can't case convert a regex and expect the same behaviour when ran on a case-converted string (because of the character groups such as \S \W).

**Comment by berlotti** [comment]
Same as for #49 : follow XSD standard of case sensitive
