### ISSUE TITLE
Are complex restrictions applicable to all facet parameters?

### ISSUE THREAD

**Issue by pierremonico** [buildingSMART/IDS#319]
The [documentation](https://github.com/buildingSMART/IDS/blob/development/Documentation/restrictions.md#complex-restrictions) states that:
```
In contrast, a **Complex Restriction** may represent pick lists of valid values, naming schemes and conventions, numeric ranges, or more. A restriction may be specified in four different ways:

 - Enumeration
 - Pattern
 - Bounds
 - Length
```

Since we're currently wrapping up the implementation of our IDS editor, we're just wondering if this really makes sense? 

From a use-case perspective, I get the point for: 
- An enumeration of possible property values
- Patterns for property values or maybe property sets
- etc.

But doesn't it get super complicated if we allow for:
- Ranges in property sets, especially combined with ranges in property values?
- Enumerations in property sets, combined with enumerations in property values? 

I believe the latter examples are not very common **(i.e. I can't find any test cases that use complex restrictions within `<propertySet>`),** lead to unreadable specifications, and can (mostly) be represented through another combination of specification? 

I am merely asking if really all parameters of all possible facets should allow for complex restrictions, or if maybe only a subset would be enough? 

We're trying to stick to the IDS spec as much as possible but even after tremendous UX efforts we feel users will have a hard time using it because of the above.

**Comment by andyward** [comment]
A pattern on PropertySet is a relatively common usage (not least to allow wildcard matches). There's a pset testcase example here: https://github.com/buildingSMART/IDS/blob/development/Documentation/testcases/property/pass-all_matching_property_sets_must_satisfy_requirements_1_3.ids

I don't see any problem combining multiple complex restrictions together for specific use cases. Just a very simple use case: _Doors and Windows should have an acoustic rating within a range_ :

**PropertySet**: _pattern_ Pset_(Door|Window)Common
**BaseName**: AcousticRating
**Value**: _bounds_ between 0 and 0.2

But clearly UXs need to adjust so that the simple case is clear/easy to both author and read, while still allowing more complex restrictions to be built. At the end of the day it's a query builder, but no doubt some queries may be considered too advanced to display in a simple interface. (perhaps similar to how some SQL queries may be too complex to edit graphically)

I can see certain complex restrictions may be inappropriate for certain facet properties. e.g. I can't see many people using Bounds or Length on a propertySet or entityName, unless there's something really esoteric going on. My general view would be that IDS verification should be comprehensive and support these edge cases, but editors may want to be more pragmatic - albeit I feel they should not be discarding / corrupting IDS content they don't support

I'm not sure that we should be deliberately limiting the functionality of IDS simply because of UX difficulties building more complex specs.  

BTW: Also worth noting an additional complexity detailed in #285 which you may want to consider in the UX - there can be multiple restrictions defined.

**Comment by pierremonico** [comment]
Thanks for the reply @andyward, that helps. Your point is valid and the example makes sense. I still think others (like range in a PropertySet) are very uncommon, but yeah, we should stay flexible. 

We will do our best to somehow catch that then.
