### ISSUE TITLE
IDS Playground editor available

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#35]
Hello all,

we have prepared a web interface for filling in IDS schemas updated to the latest version v0.5

You can test it at https://www.xbim.it/xids?bs=true

This is a web assembly application that is running entirely in your browser, and no information is exchanged with our server.

You can however save the information to XML for your purposes (and load it back for editing via drag-drop).

Any feedback is welcome.
Best,
Claudio

**Comment by CBenghi** [comment]
A quick update on the status. 
As I'm trying more complex import/export scenarios I've noticed some errors exporting due to omissions in the update to the latest changes in the schema that I'm currently addressing. I'll update the status of the application here.

**Comment by Moult** [comment]
In preparation for IDS for users, it'd be good to use this bug to track a list of implementations so that they could later be added to the implementations database.

 - https://www.xbim.it/xids?bs=true - webapp
 - https://blenderbim.org/ifctester - webapp
 - https://blenderbim.org/ - desktop app
 - IfcOpenShell https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifctester CLI/lib
 - Solibri?
 - Others? (if you post yours as a comment I can help keep this list updated to make it easy to update the database)

**Comment by pasi-paasiala** [comment]
Closing this.
