### ISSUE TITLE
How to deal with xs:restriction base attribute in relation with IfcMeasure value

### ISSUE THREAD

**Issue by berlotti** [buildingSMART/IDS#36]
IfcMeasure element is now added to properties (please review).
There are a couple of comments and open questions:
- ifcMeasure needs to 'fit' with the IFC Property of the schema (in case of using IFC properties and Psets)
- how to deal with the value of ifcMeasure, and the xs:restriction base?

For example IfcAreaMeasure is defined as being given in square meters (m2) in the IDS (defined on https://github.com/buildingSMART/IDS/wiki/Physical-Quantities-and-Units). 
For the value in the property value element it means restrictions need to be in m2. For example a pipe needs to have a value between 2 and 6 square meters. 
This means the <value> restrictions need to be addressed as:

<xs:restriction base="xs:integer">
  <xs:minInclusive value="2"/>
  <xs:maxInclusive value="6"/>
</xs:restriction>

The minInclusive and MaxInclusive are defined by the 'base' attribute in the xs:restriction element. In this example set as 'integer'. 
What is the implication of the value of this 'base' element for using fixed physical quantities and units?

**Comment by pasi-paasiala** [comment]
I think the restriction base shouldn't be integer, since the properties are almost always floating point numbers. The values in the restriction should always be given in the same based unit that is given for the measure. So if there's a requirement, that a temperature should be between 20 to 25 degrees Celsius. The limits in IDS should be 293.15 and 298.15, since temperature is given in Kelvin.

**Comment by berlotti** [comment]
This is now solved with the settlement of the measures
