### ISSUE TITLE
Multiple ifcVersion

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#40]
I guess this is a station well passed, but anyways.

Now I often have two very similar files for what is logically the same check:
- my_pretty_ids_ifc2x3.xml with ifcVersion=IFC2X3
- my_pretty_ids_ifc4.xml with ifcVersion=IFC4

To avoid creating and maintaining many duplicates of IDS specifications, would it not make more sense to allow the IDS writer to (optionally) specify multiple IFC schemas that the IDS works for? Also when validating a model, it saves the user the headache of selecting the correct version of the IDS. Adding this option would also still allow highly schema-version specific IDS checks to be created as multiple different XMLs with each only 1 ifcVersion.

So now you would have:
- my_pretty_ids_ifc2x3_ifc4.xml with ifcVersions=IFC2X3, IFC4

Another option could be to add the ability to store multiple IDS specs in one XML file, each with a different IFC schema. This way the validating software can automatically select the applicable IDS (because it already knows the schema of the IFC to be validated). This way you can distribute IDS specification by sending back and forth just one XML file and it is clear that logically the different contained specs are supposed to be equal (just different IFC schemas).

So now you would have:
- my_pretty_ids_ifc2x3_ifc4.xml with two sections, one with ifcVersion=IFC2X3 and one with ifcVersion=IFC4

**Comment by rubendel** [comment]
My suspicion is that when we keep it like it is, many implementers will add a checkbox: "Ignore IFC schema version" 

- [ ]

**Comment by aothms** [comment]
I also think this deserves some thought. I might also be that we're mixing two separate things:

* Compatibility of the IDS with versions of the IFC spec
* Requirement to have a specific version of IFC delivered

For the first we have to keep in mind that with the level of abstraction we're at (e.g material as opposed to IfcMaterialConstituentSet where the last is applicable only to certain schema versions) it should be possible to be fairly agnostic wrt ifc schema version.

For the second if this is the case it maybe should be in the specifications section and should be optional and plural.

**Comment by berlotti** [comment]
Good point. 
So suggestion is to move 'IfcVersion' to <specification> and make it a list. 
Makes sense

**Comment by CBenghi** [comment]
> * Compatibility of the IDS with versions of the IFC spec

Totally agree on this, optional is the way to go, also because this would enable to progressively define the content of IDS.
Initially the file might contain facetGroups with a just a name to work out information flows, then their technical implementation might follow, while retaining valid files.

> * Requirement to have a specific version of IFC delivered

It would help me in framing this issue to better understand the scope of a single IDS file.
If a single IDS were to cover multiple deliverables at some project stage (i.e. models provided by Arch, Stuct, MEP...) we would certainly need to expand to a list.

But I would prefer a scenario where an IDS is negotiated by provider/consumers on a more atomic level, and in that case a clear constraint to a version would make life easier for any code that goes and gets the data out of it.

Similarly to the issue I raised on the widespread use of idsValue (#39), I think that being more heavy handed on requirements would result in better workflows enabled by IDS.

**Comment by berlotti** [comment]
updated in 0.5.6
