### ISSUE TITLE
clarification of specification.use

### ISSUE THREAD

**Issue by aristotls** [buildingSMART/IDS#51]
Proposal for the definition of specification.use:

The "use" of a "specification" declares the requirement for the specification (checking rule) itself. The possible values have the following meaning:
* required --> at least 1 instance must fulfill the specification
* optional --> 0 .. * instances may fulfill the specification
* prohibited  --> all instances must not fulfill the specification (no instance is allowed to fulfill the specification)

Is this our common understanding?

**Comment by berlotti** [comment]
required --> at least 1 instance (as defined in applicability) must be in the IFC file, AND found instances must fulfil the defined requirements
optional --> when an instance is found in the IFC, it should fulfil the requirements
prohibited --> no instances (as defined in the applicability) are allowed in the file.

**Comment by aristotls** [comment]
How to express the following requirement (propably the most common one) :

when an instance (as defined in applicability) is found in the IFC, then it must fulfill the requirements ?
(but there does not need to be an instance (as defined in applicability))

**Comment by aristotls** [comment]
so your definition from above is now:
optional --> when an instance is found in the IFC, it **MUST** fulfil the requirements

**Comment by berlotti** [comment]
in my book that is the same

**Comment by aristotls** [comment]
in mine it isn't... so I propose to follow this directive from ISO, that is also used in OGC specifications:
https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor078

Then we end up with this:
* required --> at least 1 instance (as defined in applicability) **shall** be in the IFC file, AND found instances **shall** fulfil the defined requirements
* optional --> when an instance (as defined in applicability) is found in the IFC, it **shall** fulfil the requirements
* prohibited --> no instances (as defined in the applicability) **shall** be in the file.


(sorry for being so nitpick, but clarity helps in specifications )

**Comment by berlotti** [comment]
In general: 
When use is not defined, it should be interpreted as 'required'

**Comment by hesrah** [comment]
I thougt about whether "use" wouldn't be enough for applicability (as attribute of "applicability" instead of "specification") because the requirements are not effected. I think it's correct for "required" and "optional" but not for "prohibited" (?).

Maybe for clarity, we should add for "prohibited": 
_prohibited --> no instances (as defined in the applicability) shall be in the file **with this requirement**._

So, for a IDS specification with 'use="prohibited"' I could have in an IFC file an instance fit to the applicability but doesn't fulfill the requirements. Then this IFC file is valid, right?

**Comment by hesrah** [comment]
I don't know the exact status of this point. I've been offline for a while.

I have a comment and a suggestion on the nature of "use" for specification and "use" for requirements. It is my understanding that these two "use" have a different character and should not have the same name. "use" for specification is a kind of quantity or the cardinality. "use" for requirements is more like a rule scope. (Perhaps "use" isn't a good name in both cases?)

What if "use" for specification is replaced with "min-/maxOccurs" attributes? The current values "required", "optional" and "prohibited" can easily be replaced with "min-/maxOccurs"; and "min-/maxOccurs" is more general. Especially with "min-/maxOccurs" there isn't much confusion/fuzziness about the meaning of the attribute values (as actually for "required" and "optional"). Then

- "required" is 'minOccurs="1"' and 'maxOccurs="unbounded"',

- "optional" is 'minOccurs="0"' and 'maxOccurs="unbounded"' and

- "prohibited" is 'minOccurs="0"' and 'maxOccurs="0"'.

- Other possibilities are e.g. "minOccurs="2"" and "maxOccurs="2"" (exactly two).

**Comment by CBenghi** [comment]
Hi @hesrah,

I believe that @aothms makes an similar point for `use` of a requirement in the second part of his comment here: https://github.com/buildingSMART/IDS/issues/52#issuecomment-1061751135

My view is that in both cases we have not seen any use cases where we can observe a precise quantification, so it could be postponed to a later stage, should the feature be requested from users; unless, of course, you know of cases where this is already needed.

**Comment by aothms** [comment]
The reason for me to bring this up also wasn't the ability for precise quantification, but rather that specifying cardinality constraints is the typical way in schema languages to establish such requirements, see for example XSD. Plus that is generalizes and precisely specifies the meaning of the optional/requirement constructs.

**Comment by CBenghi** [comment]
@aothms,
I understand. 

The consequences, however, will be that people **might** end up specifying exact cardinality. So we will have to honour it in the verification, and probably provide a suitable UI for min and max.

Unless you are proposing that we disallow values that do not represent `optional`, `required` or `prohibited` (which would feel weird, honestly).

I'm happy with any outcome, but I feel that exact cardinality would never be much common in the industry, and that the current solution might be more easily extended when we have greater clarity of possible cardinality rules, perhaps depending on other model aspects, such as `a handrail for each stair` (I know it's a silly example, I'm just trying to express what I mean at large).

**Comment by hesrah** [comment]
I agree, the benefit isn’t in being able to express an exact cardinality. That’s not my point, this is more an “additional effect”. My point is exactly @aothms’ point if I understand him correctly.

required/optional etc. is for a single attribute value (e.g.) not for cardinality information. The “weird” convention above showing (to me) required/optional etc. is inappropriate for this.

NB: And “UI questions” should not be part of the modelling process.

**Comment by CBenghi** [comment]
> required/optional etc. is inappropriate for this.

It is not inappropriate if it's **exactly** what we want to be able to express, we might have a conversation on the wording, but the enum could serve a purpose.

>NB: And “UI questions” should not be part of the modelling process.

I was bringing that up to discuss whether full use of the cardinality is disallowed. What's your view?

**Comment by billeast** [comment]
There is indeed a need to quantify cardinality. Cardinality testing is required if data is to be part of an ecosystem that contains databases that enable team/enterprise technology. 99% of models my team and I see in practice are not suitable for anything other than rendering geometry. The following relations will need to be understood to verify requirements for the delivery/use of non-geometric data. 

The list below shows how there are different situations that must be precisely tested. You can see that the 'language-based' description of the requirement is insufficient to define exactly which type of test is to be performed. 

- (ambiguous language) (suggested language)
- (must/required) primary key                          = unique for this object type
- (must/required) compound key                     = set of unique value for object type
- (must/required) one-to-one relation              = 1..1
- (shall/required) one-to-one or more relation = 1..N
- (may/optional) one-to-zero or more relation = 0..N

While we are on the topic, there is also a need to identify "filtering" restrictions such as any provided IfcElementType's must be in the list of allowed Types.

Finally, there is a need to identify relations applicable to a given filtered set. For example, (a) at a given project stage, (b) all listed IfcElementTypes whose (c) Classification value = "X", must (c) have a set of values/properties. 

Example. without the part (c) clause: Post design but prior to equipment installation, all IfcPumpTypes must have a manufacturer and model number as well as an "approved" linked document classified as "Product Data".

Without objectively testable data relationships all the modeling in the world will be insufficient to deliver the data needed to operate and maintain facilities of any type.  This is the situation today. There is no way to disapprove a deliverable because there is no objective measure of information quality against which contracts can be written.

**Comment by billeast** [comment]
@CBenghi perhaps there is a typo?

What you suggest in the bullet list "can not" be addressed with the minOccurs and maxOccurs approach. Do you mean "can"?

Regarding "Document facet" this is a requirement of FMH-EM that was to have been included in IFC4.3. @Moult, please indicate the mapping for Document.Category that is being used.

**Comment by CBenghi** [comment]
@billeast, 
I really meant **can not**.
How do you propose that we can enforce unique primary key by specifying minOccurs and maxOccurs given the current set of facets?

**Comment by billeast** [comment]
@CBenghi okay if cardinality _**can not**_ be enforced. Then this is a "fail". 

primary and compound key testing must be provided.

cardinality testing must be provided.

If instead of fixing the inability to model and test cardinality constraints, there is a desire to use what is there already and force cardinality tests then I can only make an un-educated guess since I am not the standard expert. If instead of defining each possible test needed to enforce cardinality specifically, it is to be done with minOccurs and maxOccurs, then it is possible by having a rule with an "AND" for example 0..n is "minOccurs = 0 AND maxOccurs = 9999:". Of course having a cardinality test without ensuring unique primary keys is invalid, so that brings us back to the main problem. The need to specify and enforce primary and compound/complex keys. 

as this is a showstopper for FMH-EM @berlotti and @Moult are encouraged to weigh in here.

**Comment by CBenghi** [comment]
Dear @billeast,

> if cardinality can not be enforced. Then this is a "fail"

I did not say that.
Indeed, cardinality **can** be enforced - to some extents - with both the proposals that we are discussing here. 

What I said is that the request of your bullet points (that go beyond simple cardinality) cannot be. 
Uniqueness and cardinality can be related, but they are not the same. 

What e are discussing here has to do with cardinality; it serves a purpose and is not a fail.

> If instead of fixing the inability to model and test cardinality constraints, there is a desire to use what is there already

Not at all.
We are all carefully evaluating pros and cons of the various options to make the standard expressive, robust and elegant, so that it can live long and prosper. 👍 

If your needs for primary keys cannot be solved with what we are discussing in this thread, there is still room in other parts of the schema to address them. 

I would suggest that you start a new issue, where you can express these needs and start a conversation on how to get them incorporated in the standard, they might or might not have an impact on `use`, `minOccurs` and `maxOccurs`.

all my best,
Claudio

**Comment by billeast** [comment]
@CBenghi, So my conclusion is that however the standards team decides to do it cardinality requirements will be enforceable in some kind of IDS specification.  Thanks for the clarification and bearing with my 'end user' perspective. 

@Moult @berlotti It also appears from @CBenghi's comment that the need to enforce "primary" "compound" and "foreign" keys in IDS must be addressed in a separate thread. Would one of you start that off and include the usual suspects?

@Moult @berlotti Note from above that we also need to ensure that classification is allowed for IfcDocuments. I think we need to wait for the world turn before hearing from @Moult how this was added to IFC 4.3.

**Comment by hesrah** [comment]
It seems to me we are talking about different things. The issue here is the quantity of instances (for applicability), not the cardinality of associations.

The discussion of what basically belongs in IDS cannot be clarified here. But that seems to be resolved now.

**Comment by hesrah** [comment]
@CBenghi

> whether full use of the cardinality is disallowed

I don't quite understand what you mean by that. "cardinality is disallowed"?

**Comment by berlotti** [comment]
now using minOccurs and MaxOccurs
