### ISSUE TITLE
clarification of requirement.use

### ISSUE THREAD

**Issue by aristotls** [buildingSMART/IDS#52]
Proposal for discussion after meeting 2022-02-22:

prerequsites
* use is only available for property and attribute requirements
* use is mandatory
* in the following definitions "instance" means: instance that fulfills the applicability rules (instance of an entity)
* in the following definition "requirement" means: 
  * for attribute: name + value (if defined) 
  * for property: propertySet + name + value (if defined)

definitions for use:
* required: one property/attribute with the specified requirement shall exist for the instance
* optional: when a property/attribute with the specified name (without evaluating the value) exists for the instance, then it shall fulfill the specified requirement
* prohibited: no property/attribute with the specified requirement shall exist for the instance

**Comment by CBenghi** [comment]
Hello, 

The nature of `optional` feels wrong to me. 

The behaviour of the `optional` case, can already be achieved with the existing infrastructure: adding a property facet in the applicability that specifies `PropertySetName` and `PropertyName`, then repeat the clause in the requirement, adding the constraint on value.

The following image presents the idea of a wall with an optional property being checked for value

![image](https://user-images.githubusercontent.com/5476273/155277897-fc8c2507-d99a-45d4-b382-6678c7922afb.png)

Furthermore, we can change the nature of requirement from a list of facets to a list of `facet clauses`, each having 
- A facet (e.g. classification, property, etc.)
- An use (prohibited or required)
- Instructions

In this way we remove all the differences between facets between `applicability` and `requirement`, and remove a lot of the `<xs:extension />` from the schema, which make it harder to implement, 

Any thoughts?

**Comment by aristotls** [comment]
In your particular example you are right: there is no need for use=optional on the requirement side. But I think there could be other situations, where it will not work. 
E.g.: applicability: IfcWall --> requirement:  required Pset X and optional PSet Y and optional PSet Z

**Comment by CBenghi** [comment]
@aristotls 
Well, it would work by setting 3 specifications.
And it would allow for greater ability determine which of the constraints is optional (not just value).
I think it's much cleaner from an implementation side.

My concern is that if we inject exceptional behaviours so early in the definition of the schema, it might mean that got something wrong in the architecture.

After all the approach we are following is, "keep it as simple as possible".

:-)

**Comment by berlotti** [comment]
Use-case for optional:
"If you have information about 'x' it should be within a range, enumeration, or should be a fixed value. If you do not have that information it is not required"

So agree with definition from @aristotls :
required: one property/attribute with the specified requirement shall exist for the instance
optional: when a property/attribute with the specified **name** (without evaluating the value) exists for the instance, then it shall fulfil the specified requirement
prohibited: **no** property/attribute with the specified requirement shall exist for the instance

**Comment by CBenghi** [comment]
Hi @berlotti,
I'm not disputing the use-case for `optional`. I'm saying that it can be done with the structure that we already have, making it easier to understand and explain. And much, much easier to implement. Can we discuss in the next meeting?
Thanks

**Comment by CBenghi** [comment]
I see two parts of the issue around `use` in property requirements

1. The `optional` value
2. `required` and `prohibited` values

### The 'optional' value

The image above presents a way to remove the 'optional' use from properties.

If you add the propertyset/propertyName constraints in the applicability, and the propertyset/propertyName/PropertyValue constraint in the requirement you obtain the 'optional' case with what we already have.

![image](https://user-images.githubusercontent.com/5476273/156543770-93006545-fa71-4c77-8cc0-c3105b0c8c3d.png)

**Benefit of removing**: the facet can be implemented identically for applicability and requirement.

### 'required' and 'prohibited' values

I would argue that this has only to do with the boolean operator that we use for verification. 
Namely, `prohibited` just negates the expected result.

In my view this would be extremely simple to implement not just for Property, but for all other facets (type, attribute, classification etc.).

An extremely simple way of doing this is that `requirement` could be a collection an entity that contains:
- A facet (ifctype, property, etc)
- use (required or prohibited)
- instructions

**Benefit of change**: This takes away a lot of the use of `xs:extension` which makes implementation much simpler, and the schema easier to understand from users.

**Comment by berlotti** [comment]
1. I don't see it like that. In that case an object is defined as something with a property.
2. I'm not sure if we talk about the same kind of use-case.

For example:
applicability: ifcSpace with classification 'room' 
requirement: needs to have properties a, b, c (with or without allowed value restrictions) + 'if you have property d', then it should be within certain restrictions.

**Comment by CBenghi** [comment]
Sorry I'm not sure I understand what you mean with points 1 and 2.

But, to come to your example, the following IDS would express the case you are making, without the use of `optional`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ids:ids xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/ids.xsd" xmlns:ids="http://standards.buildingsmart.org/IDS">
	<ids:info>
		<ids:title/>
	</ids:info>
	<ids:specifications>
		<ids:specification ifcVersion="IFC4" name="Specification #1" use="optional">
			<ids:applicability>
				<ids:entity>
					<ids:name>
						<ids:simpleValue>IfcSpace</ids:simpleValue>
					</ids:name>
				</ids:entity>
				<ids:classification location="any">
					<ids:value>
						<ids:simpleValue>Room</ids:simpleValue>
					</ids:value>
				</ids:classification>
			</ids:applicability>
			<ids:requirements>
				<ids:property location="any">
					<ids:propertySet>
						<ids:simpleValue>Pset</ids:simpleValue>
					</ids:propertySet>
					<ids:name>
						<ids:simpleValue>A</ids:simpleValue>
					</ids:name>
				</ids:property>
				<ids:property location="any">
					<ids:propertySet>
						<ids:simpleValue>Pset</ids:simpleValue>
					</ids:propertySet>
					<ids:name>
						<ids:simpleValue>B</ids:simpleValue>
					</ids:name>
					<ids:value>
						<ids:simpleValue>SomeValue</ids:simpleValue>
					</ids:value>
				</ids:property>
				<ids:property location="any">
					<ids:propertySet>
						<ids:simpleValue>Pset</ids:simpleValue>
					</ids:propertySet>
					<ids:name>
						<ids:simpleValue>C</ids:simpleValue>
					</ids:name>
					<ids:value>
						<ids:simpleValue>SomeOtherValue</ids:simpleValue>
					</ids:value>
				</ids:property>
			</ids:requirements>
		</ids:specification>
		<ids:specification ifcVersion="IFC4" name="Specification #2" use="optional">
			<ids:applicability>
				<ids:entity>
					<ids:name>
						<ids:simpleValue>IfcSpace</ids:simpleValue>
					</ids:name>
				</ids:entity>
				<ids:classification location="any">
					<ids:value>
						<ids:simpleValue>Room</ids:simpleValue>
					</ids:value>
				</ids:classification>
				<ids:property location="any">
					<ids:propertySet>
						<ids:simpleValue>Pset</ids:simpleValue>
					</ids:propertySet>
					<ids:name>
						<ids:simpleValue>D</ids:simpleValue>
					</ids:name>
				</ids:property>
			</ids:applicability>
			<ids:requirements>
				<ids:property location="any">
					<ids:propertySet>
						<ids:simpleValue>Pset</ids:simpleValue>
					</ids:propertySet>
					<ids:name>
						<ids:simpleValue>D</ids:simpleValue>
					</ids:name>
					<ids:value>
						<xs:restriction base="xs:string">
							<xs:enumeration value="PossibleValue1"/>
							<xs:enumeration value="PossibleValue2"/>
						</xs:restriction>
					</ids:value>
				</ids:property>
			</ids:requirements>
		</ids:specification>
	</ids:specifications>
</ids:ids>
```

**Comment by CBenghi** [comment]
We discussed this extensively in the call today.

The broader change suggested above would result in a schema like the following:
![image](https://user-images.githubusercontent.com/5476273/157235095-a1d9a910-915f-4af9-9554-047062d456f0.png)

PROS: 
1. full symmetry between facets in the applicability/requirement parts of the specification makes for clearer user understanding.
2. Facets implementation is context independent (same implementation and UI for applicability and requirement)
3. We are extending the use (prohibited/required) to the classification, material, type and partOf.

CONS:
1. Cannot save a single specification that allows for constraint on values of optional properties, that would require to have multiple specifications.

My general concern is that producing a schema with several extensions/exceptions at version 1.0 sets a legacy of tricks to be maintained in the versions to come.

**Comment by aothms** [comment]
My take

(1)

I think Claudio is right. Optional is strictly speaking not necessary.

`A -> (B -> C)`

> If applicability A, then (if property B matching then condition C must be met)

is equivalent to

`(A & B) -> C`

> If (applicability A and property B match) then condition C must be met.

(it's been a while for me... hope I didn't make mistakes).

(1b)

But that's perhaps not the entire picture. Maybe applicability A has other additional requirements. And for that matter there might be value in keeping applicability A just that and not blending it in with the optional requirement B. Depends a bit on how you see IDS. Is it just the formal meaning that matters or is it also the structure that needs to map well onto the domain model of how the modeller has this information represented in their head.

(2)

Sorry, I have been out of the loop for far longer than I had wished. Personally I'd have preferred to have had `REQUIRED` and `PROHIBITED` expressed as cardinality constraints on the requirement.

So
* not a facet, because the cardinality constraints are to be evaluated after the facets have been taken into account
* not on applicability because we want to say. "For every wall property X must exist" and not "In the model a wall with property X must exist".
* but otherwise as high up as possible. So in this proposal you can say. For a wall:
  -  pset is forbidden
  - (pset with) property is forbidden
  - ((pset with) property with) value is forbidden
  - material/classification must exist
  - material/classification must not exist
  - ...

Required:

```
<specification>
  <applicability>
    ...
  </applicability>
  <requirement minoccurs=1>
    <prop></prop>
  </requirement>
</specification>
```

Prohibited:

```
<specification>
  <applicability>
    ...
  </applicability>
  <requirement maxoccurs=0>
    <prop></prop>
  </requirement>
</specification>
```

I think that's more in less in line with the proposal from @CBenghi

**Comment by CBenghi** [comment]
Hi @berlotti,

I was thinking further about the idea of a monolithic specification being copied from one IDS to another, and memory goes back to our implementation of the verification tool for the UK DPoW.

If my experience from that is worth anything is that it's much more likely that users will be able to reuse atomic subset of requirements rather than a single comprehensive set.

Every user I ever got in touch with, expressed the need to personalise (slightly, but invariably) the property sets proposed by theNBS to some degree, for their own 'special' needs.

I understand the lure of getting it all in a single stroke, but I wonder if this approach will be less flexible to the users, in the daily practice, with an explosion of requirements that are always different.

My expectation is that smaller `requirement sets` are more likely to be meaningful for more users. Hopefully this will not lead to one requirement per specification, but to the emergence of cohesive sets that can be cherry picked, and still allow for fast composition of an entire IDS.

Especially because my proposal only affects in this sense the 'optional' properties, and I'm not sure how pervasive this idea of 'optional extra' should be once the industry matures... People either need a property or it's an extra cost.

Sadly I won't be able to attend the call next week, but maybe we can progress the conversation here.

What do other implementers think?

**Comment by berlotti** [comment]
Actually the FM Handover is at the core of the original/current standard.
It facilitates the ‘give me all of these properties for these entities, and if you have these others you should also send them’.
Keeping that one ‘business logic’ specification is the reason why the IDS looks like it does now.

What Claudio is proposing is ‘give me all these properties for these entities. Next to that give me all of these properties (the same) for these entities (the same) that also have some others (and copy those in the specification part again to set value requirements)'.  Mainly for the sake of easier implementation.

Keeping the business logic into one specification is at the core of interoperable requirements exchange. 
Improving the standard for easier implementations is fine, but it should not go against the goals of the standard.

**Comment by CBenghi** [comment]
I think this last comment is only partially true.

> What Claudio is proposing is ‘give me all these properties for these entities. Next to that give me all of these properties (the same) for these entities (the same) that also have some others (and copy those in the specification part again to set value requirements)'. 

We are only copying the applicability adding the 'optional' facet on the applicability side, there's no duplication of the requirements.

Also, this only applies if the requirements include properties with `optional` values, otherwise there's no change.

The difference could be visualised as follows:

![image](https://user-images.githubusercontent.com/5476273/157307832-62f1544d-f85f-4e31-a3cf-6b01fb8c37d2.png)

>Mainly for the sake of easier implementation.

This is not what I said. I listed the pros above, and ease of implementation is only marginal.
The big argument for me is the clarity of the model and the removal of all extensions/exceptions, which I think are indicators of work to do.

Also, please note that I've already implemented the schema and the verification as it is... so it's not a fight I'm fighting for myself, but for what I consider the quality of the standard.

**Comment by berlotti** [comment]
As Robin (and other great men) said: Keep it as simple as possible, but not simpler.

**Comment by CBenghi** [comment]
> Keeping the business logic into one specification is at the core of interoperable requirements exchange.
Improving the standard for easier implementations is fine, but it should not go against the goals of the standard.

Sure, we just have to work on the keep it simple part. I never said that the work stops here. We can find a solution that retains all features while being simple.

For instance, we could get the best of both worlds by creating a list of SpecificationSets whithin a specification. 

![image](https://user-images.githubusercontent.com/5476273/157399632-98d13d89-f6fe-42e5-a0f4-db4ad0581939.png)

We get they symmetry, ease of understanding and implementation and retain the feature of a single business element that can be copied around. 

User interfaces could hide this grouping entirely from the UI, if they preferred to display the 'optional' flag on the single property.

**Comment by CBenghi** [comment]
@berlotti, any views on my comment above of the 9th of March?
