### ISSUE TITLE
Validity of testcases

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#96]
Most of the test cases are not valid IFC files (for example no IfcProject). For most of the testcases that is actually fine, for example a testcase about the existence of attributes. However I can imagine that not all software actually has provisions for allowing invalid IFC files to be processed. So the question is whether we could perhaps decide to only have valid IFC files? For many of the test cases IfcProject + UnitAssignments are necessary anyways, so it would also make it more consistent.

**Comment by Moult** [comment]
There's syntatic validity and other types of validity like WR. I'm tempted to say that IFC validity should be out of scope (but as a recommendation), as it would require every implementer to implement IFC validation. It would also prohibit usecases for partial IFC exchanges which are becoming increasingly popular as fileless exchanges grow.

**Comment by aothms** [comment]
Also not that for IFC4 IfcProject existence is actually not necessary anymore.

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD1/HTML/schema/ifckernel/lexical/ifcsingleprojectinstance.htm

**Comment by rubendel** [comment]
Not saying that every implementation should implement IFC validation as part of IDS validation. Was only talking about the testcases. But @aothms has a good point about IfcProject not being required anymore. In general (outside of IDS context) does make me wonder what should be considered the default units when those are not defined.

**Comment by aothms** [comment]
We're digressing, but:

I guess the rule was changed because you in IFC4 IfcProjectLibrary was introduced. The natural change would have been to change it to SIZEOF(IfcContext) == 1, but I guess they didn't want to provide an upper bound the number of project libraries in a file and also want to somehow open the door to partial exchanges.

@TLiebich do you recall the considerations here?

For units I guess it strictly doesn't change much because there was never any rule in place for the IfcUnitAssignment to actually be present or carry a reasonable set of units.

Secondly, SI units as a default seems to make sense. Is this all documented somewhere? Should it?
